apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rpl4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-rpl4@sha256:410eb4c3d72020a8aa5c2bc0280d011643819caac6a2d924243ac2dc315605d4
        name: my-nodejs
        resources: {}
status: {}
